### PR TITLE
Add a link to the project repository in the contribution section

### PR DESCRIPTION
**Pull request by asavageiv**

### CODE REVIEW

**Comment by koic** [comment]
Nice improvement!

**Comment by pirj** [comment]
Thanks!

@koic It's kind of unfortunate that Ruby/Rails/RSpec guides don't have a Github badge somewhere in the top-right corner of their front pages. Would that make a good addition from your standpoint?

**Comment by bbatsov** [comment]
Something like "Fork me on GitHub"? Yeah, I think that'd be useful.

**Comment by koic** [comment]
I agree with @pirj's idea 👍 IMHO, the guides aren't permanently decided, and I hope users can make better improvements as Ruby, Rails, RSpec, and Community grow.

**Comment by pirj** [comment]
Sorry, I'm busy with other things next couple of weeks, but this is on my list. Unless @asavageiv you want to tackle making those changes across our guides first.

**Pull request merged**
