### PR TITLE
Prefer symbol arguments to callbacks

### PR DESCRIPTION
**Pull request by mattbeedle**

### CODE REVIEW

**Comment by cesc1989** [comment]
Agreed with this PR

**Comment by andyw8** [comment]
Perhaps there could be be a configuration option of `MaxLinesInCallbackBody`, with a default of 5 or so.

**Comment by mattbeedle** [comment]
Another reason why it's preferable is that you can then skip them with [`MyModel.skip_callback`](http://apidock.com/rails/ActiveSupport/Callbacks/ClassMethods/skip_callback) method. I don't think that's possible with the block style.

**Comment by pirj** [comment]
Closing as stale.

**Pull request closed without merging**
