### PR TITLE
Update ruby formatter

### PR DESCRIPTION
**Pull request by vs4vijay**
Update ruby formatter

### CODE REVIEW

**Comment by bbatsov** [comment]
Not sure what the point of this PR is.

**Comment by vs4vijay** [comment]
Format Issue Image

@bbatsov Changed markdown, as it doesn't render properly. See screenshot for ref.

**Comment by KevinBongart** [comment]
To me, this is more about function than style: the bad option just won't work, and the Rails docs already explain how to use these two methods correctly. @vs4vijay, do you agree with how I see the difference between this Rails style guide and the Rails docs?

**Comment by andyw8** [comment]
This section was removed in #239.

**Pull request closed without merging**
